# Generated by Django 3.1.7 on 2021-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='Jeff', max_length=20),
        ),
    ]
